# Generated by Django 5.1.7 on 2025-03-23 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_blogcategory_blogpost_blogcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='has_moderator_request',
            field=models.BooleanField(default=False, help_text='Indicates if a moderator has been requested for this inquiry'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='moderator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MODERATOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description of what this payment is for')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(limit_choices_to={'role': 'BUSINESS'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='accounts.inquiry')),
                ('recipient', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request', to='accounts.transaction')),
            ],
        ),
    ]
