# Generated by Django 5.1.7 on 2025-04-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_conversation_conversationmessage_and_more'),
    ]

    operations = [
        # This is an empty migration to synchronize the model with the database
        # The expertise field already exists in the database
    ]
