# Generated by Django 5.1.7 on 2025-04-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20250411_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_customer',
            field=models.BooleanField(default=False, help_text='Flag indicating if the customer has been verified'),
        ),
    ]
