# Generated by Django 5.1.7 on 2025-04-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_is_verified_customer'),
    ]

    operations = [
        # Mark the migration as complete even though it doesn't need to do anything
        # because the columns already exist in the database
        migrations.RunSQL(
            sql="SELECT 1;",  # Do nothing SQL that won't cause an error
            reverse_sql="SELECT 1;"
        ),
    ]
