# Generated by Django 5.1.7 on 2025-04-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20250411_2018'),
    ]

    operations = [
        # This is a fake migration to sync the model with the database state
        # No need to actually apply changes as column already exists
    ]
