# Generated by Django 5.1.7 on 2025-04-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.TextField(blank=True, default='', help_text="User's areas of expertise"),
        ),
    ]
