# Generated by Django 5.1.7 on 2025-04-21 03:25

from decimal import Decimal
import random
from django.db import migrations, models


def set_random_prices(apps, schema_editor):
    """Set random fixed prices for existing services (between 0 and 20 euros)"""
    Service = apps.get_model('accounts', 'Service')
    for service in Service.objects.all():
        # Random price between 0 and 20 with 2 decimal places
        price = round(random.uniform(0, 20), 2)
        # 20% chance of being free (0 price)
        if random.random() < 0.2:
            price = 0
        service.fixed_price = Decimal(str(price))
        service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_expertise_field_explicitly'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed price to open an inquiry chat (0 for free)', max_digits=10),
        ),
        migrations.RunPython(set_random_prices, migrations.RunPython.noop),
    ]
