# Generated by Django 5.1.7 on 2025-04-28 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedServiceCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='verified_service_records', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_customer_records', to='accounts.service')),
                ('verified_by', models.ForeignKey(limit_choices_to={'role': 'MODERATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verified Service Customer',
                'verbose_name_plural': 'Verified Service Customers',
                'unique_together': {('service', 'customer')},
            },
        ),
        migrations.AddField(
            model_name='service',
            name='verified_customers',
            field=models.ManyToManyField(blank=True, help_text='Customers who are verified to review this service', related_name='verified_services', through='accounts.VerifiedServiceCustomer', to=settings.AUTH_USER_MODEL),
        ),
    ]
