# Generated by Django 5.1.7 on 2025-04-29 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_verifiedservicecustomer_service_verified_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportconversation',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='supportconversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='sender',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='The customer who wrote the review', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ServiceReport',
        ),
        migrations.DeleteModel(
            name='SupportConversation',
        ),
        migrations.DeleteModel(
            name='SupportMessage',
        ),
    ]
