# Uncomment this if you want to use the standard Nginx-based Dockerfile
[build]
builder = "DOCKERFILE"
#dockerfilePath = "Dockerfile"

# Uncomment these lines if you want to try the Node.js-based Dockerfile instead
#[build]
#builder = "DOCKERFILE"
#dockerfilePath = "Dockerfile.node"

[deploy]
numReplicas = 1
healthcheck = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
port = 80