version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_ENV=development
      - DATABASE_URL=mysql://root:password@db:3306/urbanlife
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_SUPERUSER_USERNAME=admin
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=urbanlife
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: