[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.railway"

[deploy]
startCommand = "python -m http.server 8000"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
port = 8000

[vars]
DJANGO_ENV = "production"
DJANGO_SECRET_KEY = "MGgX9a8un0KMRrDCb02hnwWCIwi+D01Gb1tSfTkQCf8="
ALLOWED_HOSTS = "*.up.railway.app"