[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.railway"

[deploy]
startCommand = "python manage.py migrate && gunicorn --bind 0.0.0.0:$PORT core.wsgi:application"
healthcheckPath = "/api/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[vars]
DJANGO_ENV = "production"
DJANGO_SECRET_KEY = "MGgX9a8un0KMRrDCb02hnwWCIwi+D01Gb1tSfTkQCf8="
ALLOWED_HOSTS = "*.up.railway.app"