[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile.railway"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
# Re-enable health checks
healthcheckPath = "/api/health/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
port = 8000

[vars]
DJANGO_ENV = "production"
DJANGO_SECRET_KEY = "MGgX9a8un0KMRrDCb02hnwWCIwi+D01Gb1tSfTkQCf8="
ALLOWED_HOSTS = "*.up.railway.app"